### ISSUE TITLE
systemd-nspawn redirect dance

### ISSUE THREAD

**Issue by JayAndCatchFire** [Friz-zy/awesome-linux-containers#19]
The link for systemd-nspawn, currently http://manpages.ubuntu.com/manpages/utopic/man1/systemd-nspawn.1.html, does a redirect dance due to Ubuntu's frequent releases.  It currently redirects (after a couple of hops) to http://manpages.ubuntu.com/manpages/xenial/en/man1/systemd-nspawn.1.html.

This isn't a problem per se.  But maybe consider changing the link to something more stable such as the following:
- https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html
- https://www.commandlinux.com/man-page/man1/systemd-nspawn.1.html

**Comment by Friz-zy** [comment]
Fixed in 39577b0195d658dbce7520e69bfd6f94d5d97731 by adding link from Arch wiki
Thank you!
